name: GitHub-Profile-Summary-Cards

on:
  create:
  push:
  schedule: # Run Workflow at 00:01 on January 1, March 1, June 1, September 1, and December 1 — five times a year.
    - cron: "1 0 1 jan,mar,jun,sep,dec *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-cards
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v2
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
